#!/bin/bash
#log-archive - Archive log files iwth timestamp
#auther - Pasindu Kaveesha Meepawala

#check if the user provided a directory
if [ -z "$1" ]; then
	echo "Usage: $0 <log-directory>"
	exit 1
fi

LOG_DIR=$1

#check if the directory exists
if [ ! -d "$LOG_DIR" ]; then
	echo "Error: Directory $LOG_DIR does not exist."
	exit 1
fi

echo "Log directory provided: $LOG_DIR" 
