#!/bin/bash
#log-archive - Archive log files iwth timestamp
#auther - Pasindu Kaveesha Meepawala

#check if the user provided a directory
if [ -z "$1" ]; then
	echo "Usage: $0 <log-directory>"
	exit 1
fi

LOG_DIR=$1

#check if the directory exists
if [ ! -d "$LOG_DIR" ]; then
	echo "Error: Directory $LOG_DIR does not exist."
	exit 1
fi

echo "Log directory provided: $LOG_DIR" 

#create directory to store archives (if it doesn't exist)
ARCHIVE_DIR="archived_logs"
mkdir -p "$ARCHIVE_DIR"

TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
ARCHIVE_NAME="logs_archive_${TIMESTAMP}.tar.gz"

#compress the logs
tar -czf "$ARCHIVE_DIR/$ARCHIVE_NAME" -C "$LOG_DIR" .

echo "Archive created successfully!"
echo "Saved to: $ARCHIVE_DIR/$ARCHIVE_NAME"

# Log the archive action
echo "$(date): Archived $LOG_DIR to $ARCHIVE_DIR/$ARCHIVE_NAME" >> archive.log

echo "Archive log updated: archive.log"
